# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestingcreateaccount():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testingcreateaccount(self):
    self.driver.get("https://gopro.com/en/us/")
    self.driver.set_window_size(1292, 692)
    self.driver.find_element(By.LINK_TEXT, "Account").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login .btn-google > .btn-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".eARute > .lCoei").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "identifierId").click()
    self.driver.find_element(By.ID, "identifierId").click()
    element = self.driver.find_element(By.ID, "identifierId")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "identifierId").click()
    self.driver.find_element(By.ID, "identifierId").send_keys("testerhaneen@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb").click()
    self.driver.find_element(By.NAME, "password").send_keys("Hha12345")
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gpl-icon-close").click()
    self.driver.find_element(By.LINK_TEXT, "Continue with Google").click()
    self.driver.find_element(By.CSS_SELECTOR, ".eARute > .lCoei").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "identifierId").click()
    self.driver.find_element(By.ID, "identifierId").click()
    element = self.driver.find_element(By.ID, "identifierId")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "identifierId").click()
    self.driver.find_element(By.ID, "identifierId").send_keys("testerhaneen@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d").click()
    self.driver.find_element(By.NAME, "password").send_keys("Hha12345")
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Hha12345")
    self.driver.find_element(By.NAME, "confirmPassword").click()
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("Hha12345")
    self.driver.find_element(By.CSS_SELECTOR, ".gp-form-row:nth-child(3) > .gp-checkbox > label").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
  
